name: Deploy to Server via SCP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: mkdir -p ~/.ssh && chmod 700 ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && cat ~/.ssh/id_rsa

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: 24.144.93.173
          username: root
          key: ~/.ssh/id_rsa  # Use key-based authentication
          source: "."  # Local directory to copy
          target: "/var/www/html"  # Remote directory on the server
